// <auto-generated />
using Wojtalak_Szczerkowski.GameApp.DAOSQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Wojtalak_Szczerkowski.GameApp.DAOSQLite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240128174558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("GameApp.DAOSQLite.BO.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("GameApp.DAOSQLite.BO.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_developerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("_developerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameApp.DAOSQLite.BO.Game", b =>
                {
                    b.HasOne("GameApp.DAOSQLite.BO.Developer", "_developer")
                        .WithMany()
                        .HasForeignKey("_developerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_developer");
                });
#pragma warning restore 612, 618
        }
    }
}
